/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GSNRecipientERC20Fee__factory } from "./GSNRecipientERC20Fee__factory";
export { __unstable__ERC20Owned__factory } from "./__unstable__ERC20Owned__factory";
