/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../../../common";
import type {
  EtherReceiverMock,
  EtherReceiverMockInterface,
} from "../../../../../../../contracts/lib/uniswap/openzeppelin/contracts/mocks/EtherReceiverMock";

const _abi = [
  {
    inputs: [
      {
        internalType: "bool",
        name: "acceptEther",
        type: "bool",
      },
    ],
    name: "setAcceptEther",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060a38061001e6000396000f3fe608060405260043610601f5760003560e01c80634fea120c146038576033565b3660335760005460ff16603157600080fd5b005b600080fd5b348015604357600080fd5b50603160048036036020811015605857600080fd5b506000805460ff19169135151591909117905556fea2646970667358221220e189359ff79a2ec293e251a97741e2bda5e8db3018f15d76a306bd10b910e32b64736f6c63430007060033";

type EtherReceiverMockConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EtherReceiverMockConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class EtherReceiverMock__factory extends ContractFactory {
  constructor(...args: EtherReceiverMockConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      EtherReceiverMock & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): EtherReceiverMock__factory {
    return super.connect(runner) as EtherReceiverMock__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EtherReceiverMockInterface {
    return new Interface(_abi) as EtherReceiverMockInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): EtherReceiverMock {
    return new Contract(address, _abi, runner) as unknown as EtherReceiverMock;
  }
}
