/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as gsnRecipientErc20FeeSol from "./GSNRecipientERC20Fee.sol";
export { GSNRecipient__factory } from "./GSNRecipient__factory";
export { GSNRecipientSignature__factory } from "./GSNRecipientSignature__factory";
export { IRelayHub__factory } from "./IRelayHub__factory";
export { IRelayRecipient__factory } from "./IRelayRecipient__factory";
