/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../../../common";

export interface GSNRecipientInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptRelayedCall"
      | "getHubAddr"
      | "postRelayedCall"
      | "preRelayedCall"
      | "relayHubVersion"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "RelayHubChanged"): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptRelayedCall",
    values: [
      AddressLike,
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getHubAddr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "postRelayedCall",
    values: [BytesLike, boolean, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "preRelayedCall",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "relayHubVersion",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptRelayedCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getHubAddr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "postRelayedCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "preRelayedCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "relayHubVersion",
    data: BytesLike
  ): Result;
}

export namespace RelayHubChangedEvent {
  export type InputTuple = [oldRelayHub: AddressLike, newRelayHub: AddressLike];
  export type OutputTuple = [oldRelayHub: string, newRelayHub: string];
  export interface OutputObject {
    oldRelayHub: string;
    newRelayHub: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GSNRecipient extends BaseContract {
  connect(runner?: ContractRunner | null): GSNRecipient;
  waitForDeployment(): Promise<this>;

  interface: GSNRecipientInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptRelayedCall: TypedContractMethod<
    [
      relay: AddressLike,
      from: AddressLike,
      encodedFunction: BytesLike,
      transactionFee: BigNumberish,
      gasPrice: BigNumberish,
      gasLimit: BigNumberish,
      nonce: BigNumberish,
      approvalData: BytesLike,
      maxPossibleCharge: BigNumberish
    ],
    [[bigint, string]],
    "view"
  >;

  getHubAddr: TypedContractMethod<[], [string], "view">;

  postRelayedCall: TypedContractMethod<
    [
      context: BytesLike,
      success: boolean,
      actualCharge: BigNumberish,
      preRetVal: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  preRelayedCall: TypedContractMethod<
    [context: BytesLike],
    [string],
    "nonpayable"
  >;

  relayHubVersion: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptRelayedCall"
  ): TypedContractMethod<
    [
      relay: AddressLike,
      from: AddressLike,
      encodedFunction: BytesLike,
      transactionFee: BigNumberish,
      gasPrice: BigNumberish,
      gasLimit: BigNumberish,
      nonce: BigNumberish,
      approvalData: BytesLike,
      maxPossibleCharge: BigNumberish
    ],
    [[bigint, string]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getHubAddr"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "postRelayedCall"
  ): TypedContractMethod<
    [
      context: BytesLike,
      success: boolean,
      actualCharge: BigNumberish,
      preRetVal: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "preRelayedCall"
  ): TypedContractMethod<[context: BytesLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "relayHubVersion"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "RelayHubChanged"
  ): TypedContractEvent<
    RelayHubChangedEvent.InputTuple,
    RelayHubChangedEvent.OutputTuple,
    RelayHubChangedEvent.OutputObject
  >;

  filters: {
    "RelayHubChanged(address,address)": TypedContractEvent<
      RelayHubChangedEvent.InputTuple,
      RelayHubChangedEvent.OutputTuple,
      RelayHubChangedEvent.OutputObject
    >;
    RelayHubChanged: TypedContractEvent<
      RelayHubChangedEvent.InputTuple,
      RelayHubChangedEvent.OutputTuple,
      RelayHubChangedEvent.OutputObject
    >;
  };
}
