/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gsnRecipientErc20FeeSol from "./GSNRecipientERC20Fee.sol";
export type { gsnRecipientErc20FeeSol };
export type { GSNRecipient } from "./GSNRecipient";
export type { GSNRecipientSignature } from "./GSNRecipientSignature";
export type { IRelayHub } from "./IRelayHub";
export type { IRelayRecipient } from "./IRelayRecipient";
