/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../../../common";

export interface Create2ImplInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "computeAddress"
      | "computeAddressWithDeployer"
      | "deploy"
      | "deployERC1820Implementer"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "computeAddress",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "computeAddressWithDeployer",
    values: [BytesLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deploy",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deployERC1820Implementer",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "computeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeAddressWithDeployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deploy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployERC1820Implementer",
    data: BytesLike
  ): Result;
}

export interface Create2Impl extends BaseContract {
  connect(runner?: ContractRunner | null): Create2Impl;
  waitForDeployment(): Promise<this>;

  interface: Create2ImplInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  computeAddress: TypedContractMethod<
    [salt: BytesLike, codeHash: BytesLike],
    [string],
    "view"
  >;

  computeAddressWithDeployer: TypedContractMethod<
    [salt: BytesLike, codeHash: BytesLike, deployer: AddressLike],
    [string],
    "view"
  >;

  deploy: TypedContractMethod<
    [value: BigNumberish, salt: BytesLike, code: BytesLike],
    [void],
    "nonpayable"
  >;

  deployERC1820Implementer: TypedContractMethod<
    [value: BigNumberish, salt: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "computeAddress"
  ): TypedContractMethod<
    [salt: BytesLike, codeHash: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "computeAddressWithDeployer"
  ): TypedContractMethod<
    [salt: BytesLike, codeHash: BytesLike, deployer: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "deploy"
  ): TypedContractMethod<
    [value: BigNumberish, salt: BytesLike, code: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deployERC1820Implementer"
  ): TypedContractMethod<
    [value: BigNumberish, salt: BytesLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
