/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../../../common";

export interface EnumerableMapMockInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "at"
      | "contains"
      | "get"
      | "getWithMessage"
      | "length"
      | "remove"
      | "set"
      | "tryGet"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "OperationResult"): EventFragment;

  encodeFunctionData(functionFragment: "at", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "contains",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "get", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getWithMessage",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "length", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "remove",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "set",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tryGet",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "at", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "contains", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "get", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getWithMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "length", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "remove", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "set", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tryGet", data: BytesLike): Result;
}

export namespace OperationResultEvent {
  export type InputTuple = [result: boolean];
  export type OutputTuple = [result: boolean];
  export interface OutputObject {
    result: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EnumerableMapMock extends BaseContract {
  connect(runner?: ContractRunner | null): EnumerableMapMock;
  waitForDeployment(): Promise<this>;

  interface: EnumerableMapMockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  at: TypedContractMethod<
    [index: BigNumberish],
    [[bigint, string] & { key: bigint; value: string }],
    "view"
  >;

  contains: TypedContractMethod<[key: BigNumberish], [boolean], "view">;

  get: TypedContractMethod<[key: BigNumberish], [string], "view">;

  getWithMessage: TypedContractMethod<
    [key: BigNumberish, errorMessage: string],
    [string],
    "view"
  >;

  length: TypedContractMethod<[], [bigint], "view">;

  remove: TypedContractMethod<[key: BigNumberish], [void], "nonpayable">;

  set: TypedContractMethod<
    [key: BigNumberish, value: AddressLike],
    [void],
    "nonpayable"
  >;

  tryGet: TypedContractMethod<[key: BigNumberish], [[boolean, string]], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "at"
  ): TypedContractMethod<
    [index: BigNumberish],
    [[bigint, string] & { key: bigint; value: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "contains"
  ): TypedContractMethod<[key: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "get"
  ): TypedContractMethod<[key: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getWithMessage"
  ): TypedContractMethod<
    [key: BigNumberish, errorMessage: string],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "length"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "remove"
  ): TypedContractMethod<[key: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "set"
  ): TypedContractMethod<
    [key: BigNumberish, value: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tryGet"
  ): TypedContractMethod<[key: BigNumberish], [[boolean, string]], "view">;

  getEvent(
    key: "OperationResult"
  ): TypedContractEvent<
    OperationResultEvent.InputTuple,
    OperationResultEvent.OutputTuple,
    OperationResultEvent.OutputObject
  >;

  filters: {
    "OperationResult(bool)": TypedContractEvent<
      OperationResultEvent.InputTuple,
      OperationResultEvent.OutputTuple,
      OperationResultEvent.OutputObject
    >;
    OperationResult: TypedContractEvent<
      OperationResultEvent.InputTuple,
      OperationResultEvent.OutputTuple,
      OperationResultEvent.OutputObject
    >;
  };
}
