/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../../../common";

export interface ERC165CheckerMockInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getSupportedInterfaces"
      | "supportsAllInterfaces"
      | "supportsERC165"
      | "supportsInterface"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getSupportedInterfaces",
    values: [AddressLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsAllInterfaces",
    values: [AddressLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsERC165",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getSupportedInterfaces",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsAllInterfaces",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsERC165",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
}

export interface ERC165CheckerMock extends BaseContract {
  connect(runner?: ContractRunner | null): ERC165CheckerMock;
  waitForDeployment(): Promise<this>;

  interface: ERC165CheckerMockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getSupportedInterfaces: TypedContractMethod<
    [account: AddressLike, interfaceIds: BytesLike[]],
    [boolean[]],
    "view"
  >;

  supportsAllInterfaces: TypedContractMethod<
    [account: AddressLike, interfaceIds: BytesLike[]],
    [boolean],
    "view"
  >;

  supportsERC165: TypedContractMethod<
    [account: AddressLike],
    [boolean],
    "view"
  >;

  supportsInterface: TypedContractMethod<
    [account: AddressLike, interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getSupportedInterfaces"
  ): TypedContractMethod<
    [account: AddressLike, interfaceIds: BytesLike[]],
    [boolean[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "supportsAllInterfaces"
  ): TypedContractMethod<
    [account: AddressLike, interfaceIds: BytesLike[]],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "supportsERC165"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<
    [account: AddressLike, interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  filters: {};
}
