/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BeaconProxy__factory } from "./BeaconProxy__factory";
export { IBeacon__factory } from "./IBeacon__factory";
export { Proxy__factory } from "./Proxy__factory";
export { ProxyAdmin__factory } from "./ProxyAdmin__factory";
export { TransparentUpgradeableProxy__factory } from "./TransparentUpgradeableProxy__factory";
export { UpgradeableBeacon__factory } from "./UpgradeableBeacon__factory";
export { UpgradeableProxy__factory } from "./UpgradeableProxy__factory";
