/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../../../../common";
import type {
  SampleHuman,
  SampleHumanInterface,
} from "../../../../../../../../contracts/lib/uniswap/openzeppelin/contracts/mocks/MultipleInheritanceInitializableMocks.sol/SampleHuman";

const _abi = [
  {
    inputs: [],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "isHuman",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610219806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80634a6c9db61461003b5780638129fc1c1461005b575b600080fd5b610043610065565b60405180821515815260200191505060405180910390f35b610063610078565b005b600060029054906101000a900460ff1681565b600060019054906101000a900460ff16806100975750610096610191565b5b806100ad575060008054906101000a900460ff16155b610102576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602e8152602001806101b6602e913960400191505060405180910390fd5b60008060019054906101000a900460ff161590508015610152576001600060016101000a81548160ff02191690831515021790555060016000806101000a81548160ff0219169083151502179055505b6001600060026101000a81548160ff021916908315150217905550801561018e5760008060016101000a81548160ff0219169083151502179055505b50565b600061019c306101a2565b15905090565b600080823b90506000811191505091905056fe496e697469616c697a61626c653a20636f6e747261637420697320616c726561647920696e697469616c697a6564a26469706673582212207da70ca6e45e45d2085ec72ea505183b3851d24a1ed40f5714633d896bdc16d864736f6c63430007060033";

type SampleHumanConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SampleHumanConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SampleHuman__factory extends ContractFactory {
  constructor(...args: SampleHumanConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SampleHuman & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): SampleHuman__factory {
    return super.connect(runner) as SampleHuman__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SampleHumanInterface {
    return new Interface(_abi) as SampleHumanInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): SampleHuman {
    return new Contract(address, _abi, runner) as unknown as SampleHuman;
  }
}
