env: "prod"
features:
  devMode: false
cors:
  specificOriginRegExp: ^https://(.*)[.]bondefi[.]xyz$
frontend:
  url: "https://bondefi.xyz"
radix:
  networkId: 2
  managerComponentId: 'component_tdx_2_1cqru64adgqfheal7e9lvzqf0thnfdvzg74pdkmec06drg7u4vh3fgd'
  managerTokenId: 'resource_tdx_2_1n2d0azptpw86zrj39uunvzcujxg6lmm74705h0qqfzrl5qa894a2ac'
  appName: 'Bondefi'
  appVersion: '1.0.1'
  dAppDefinition: 'account_tdx_2_128evrrwfp8gj9240qq0m06ukhwaj2cmejluxxreanzjwq62vmlf8r4'