/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../../../../common";
import type {
  Implementation3,
  Implementation3Interface,
} from "../../../../../../../../contracts/lib/uniswap/openzeppelin/contracts/mocks/RegressionImplementation.sol/Implementation3";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_number",
        type: "uint256",
      },
    ],
    name: "getValue",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_number",
        type: "uint256",
      },
    ],
    name: "setValue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506101c5806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80630ff4c9161461004657806355241077146100755780638129fc1c14610094575b600080fd5b6100636004803603602081101561005c57600080fd5b503561009c565b60408051918252519081900360200190f35b6100926004803603602081101561008b57600080fd5b50356100a3565b005b6100926100a8565b6001540190565b600155565b600054610100900460ff16806100c157506100c161014a565b806100cf575060005460ff16155b61010a5760405162461bcd60e51b815260040180806020018281038252602e815260200180610162602e913960400191505060405180910390fd5b600054610100900460ff16158015610135576000805460ff1961ff0019909116610100171660011790555b8015610147576000805461ff00191690555b50565b60006101553061015b565b15905090565b3b15159056fe496e697469616c697a61626c653a20636f6e747261637420697320616c726561647920696e697469616c697a6564a2646970667358221220a0a0e35726e11690748c93acf04904e6eefd03a433d63348981520da79e5ab7064736f6c63430007060033";

type Implementation3ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: Implementation3ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Implementation3__factory extends ContractFactory {
  constructor(...args: Implementation3ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Implementation3 & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Implementation3__factory {
    return super.connect(runner) as Implementation3__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): Implementation3Interface {
    return new Interface(_abi) as Implementation3Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): Implementation3 {
    return new Contract(address, _abi, runner) as unknown as Implementation3;
  }
}
